from datetime import date, time

from app.models import LimitUpEvent, MarketIndexSnapshot


SAMPLE_INDICES: list[MarketIndexSnapshot] = [
    MarketIndexSnapshot(
        name="上证指数",
        symbol="000001.SH",
        close=3678.42,
        change_pct=0.82,
        trend=[3638.2, 3645.8, 3651.4, 3664.9, 3678.42],
    ),
    MarketIndexSnapshot(
        name="深证成指",
        symbol="399001.SZ",
        close=11246.31,
        change_pct=1.18,
        trend=[11102.6, 11138.5, 11180.2, 11204.8, 11246.31],
    ),
    MarketIndexSnapshot(
        name="创业板指",
        symbol="399006.SZ",
        close=2389.76,
        change_pct=-0.24,
        trend=[2401.4, 2398.1, 2384.6, 2391.2, 2389.76],
    ),
]


SAMPLE_EVENTS: list[LimitUpEvent] = [
    LimitUpEvent(
        symbol="002230",
        name="科大讯飞",
        trade_date=date(2026, 5, 15),
        first_limit_time=time(9, 36),
        last_limit_time=time(14, 58),
        seal_count=2,
        break_count=1,
        closed_limit=True,
        board_height=3,
        amount=6_210_000_000,
        turnover_rate=7.1,
        industry="软件开发",
        concept="人工智能",
        next_open_pct=4.2,
        next_high_pct=9.8,
        next_close_pct=6.4,
        three_day_return_pct=10.7,
        five_day_return_pct=14.2,
        continued_next_day=True,
    ),
    LimitUpEvent(
        symbol="600519",
        name="贵州茅台",
        trade_date=date(2026, 5, 15),
        first_limit_time=time(9, 32),
        last_limit_time=time(9, 32),
        seal_count=1,
        break_count=0,
        closed_limit=True,
        board_height=4,
        amount=7_980_000_000,
        turnover_rate=1.4,
        industry="白酒",
        concept="消费",
        next_open_pct=2.9,
        next_high_pct=6.8,
        next_close_pct=3.6,
        three_day_return_pct=8.9,
        five_day_return_pct=11.7,
        continued_next_day=False,
    ),
    LimitUpEvent(
        symbol="301489",
        name="思泉新材",
        trade_date=date(2026, 5, 15),
        first_limit_time=time(9, 48),
        last_limit_time=time(13, 57),
        seal_count=3,
        break_count=2,
        closed_limit=True,
        board_height=1,
        amount=1_240_000_000,
        turnover_rate=18.6,
        industry="消费电子",
        concept="AI 端侧",
        next_open_pct=1.6,
        next_high_pct=5.2,
        next_close_pct=2.4,
        three_day_return_pct=4.9,
        five_day_return_pct=6.8,
        continued_next_day=True,
    ),
    LimitUpEvent(
        symbol="603083",
        name="剑桥科技",
        trade_date=date(2026, 5, 15),
        first_limit_time=time(10, 17),
        last_limit_time=time(14, 44),
        seal_count=5,
        break_count=4,
        closed_limit=False,
        board_height=1,
        amount=3_860_000_000,
        turnover_rate=14.2,
        industry="通信设备",
        concept="CPO",
        next_open_pct=-1.8,
        next_high_pct=1.7,
        next_close_pct=-3.5,
        three_day_return_pct=-4.1,
        five_day_return_pct=-5.9,
        continued_next_day=False,
    ),
    LimitUpEvent(
        symbol="002050",
        name="三花智控",
        trade_date=date(2026, 5, 15),
        first_limit_time=time(13, 11),
        last_limit_time=time(14, 51),
        seal_count=4,
        break_count=3,
        closed_limit=False,
        board_height=1,
        amount=4_540_000_000,
        turnover_rate=5.9,
        industry="汽车零部件",
        concept="机器人",
        next_open_pct=-0.6,
        next_high_pct=2.3,
        next_close_pct=-1.1,
        three_day_return_pct=0.8,
        five_day_return_pct=2.2,
        continued_next_day=False,
    ),
    LimitUpEvent(
        symbol="000001",
        name="平安银行",
        trade_date=date(2026, 5, 14),
        first_limit_time=time(9, 41),
        last_limit_time=time(14, 52),
        seal_count=3,
        break_count=2,
        closed_limit=True,
        board_height=1,
        amount=3_250_000_000,
        turnover_rate=2.8,
        industry="银行",
        concept="大金融",
        next_open_pct=1.4,
        next_high_pct=4.1,
        next_close_pct=2.2,
        three_day_return_pct=3.8,
        five_day_return_pct=5.4,
        continued_next_day=False,
    ),
    LimitUpEvent(
        symbol="300750",
        name="宁德时代",
        trade_date=date(2026, 5, 14),
        first_limit_time=time(13, 25),
        last_limit_time=time(14, 49),
        seal_count=4,
        break_count=3,
        closed_limit=False,
        board_height=1,
        amount=8_640_000_000,
        turnover_rate=3.9,
        industry="电池",
        concept="新能源车",
        next_open_pct=-0.8,
        next_high_pct=2.9,
        next_close_pct=-1.6,
        three_day_return_pct=-0.4,
        five_day_return_pct=1.1,
        continued_next_day=False,
    ),
    LimitUpEvent(
        symbol="601012",
        name="隆基绿能",
        trade_date=date(2026, 5, 14),
        first_limit_time=time(11, 12),
        last_limit_time=time(14, 54),
        seal_count=5,
        break_count=4,
        closed_limit=True,
        board_height=2,
        amount=4_970_000_000,
        turnover_rate=5.5,
        industry="光伏设备",
        concept="光伏",
        next_open_pct=0.6,
        next_high_pct=3.4,
        next_close_pct=-2.3,
        three_day_return_pct=-3.5,
        five_day_return_pct=-4.7,
        continued_next_day=False,
    ),
    LimitUpEvent(
        symbol="300124",
        name="汇川技术",
        trade_date=date(2026, 5, 13),
        first_limit_time=time(10, 8),
        last_limit_time=time(14, 56),
        seal_count=2,
        break_count=1,
        closed_limit=True,
        board_height=1,
        amount=3_790_000_000,
        turnover_rate=3.7,
        industry="自动化设备",
        concept="机器人",
        next_open_pct=2.1,
        next_high_pct=6.4,
        next_close_pct=4.6,
        three_day_return_pct=7.2,
        five_day_return_pct=9.3,
        continued_next_day=True,
    ),
    LimitUpEvent(
        symbol="688256",
        name="寒武纪",
        trade_date=date(2026, 5, 13),
        first_limit_time=time(9, 55),
        last_limit_time=time(13, 46),
        seal_count=3,
        break_count=2,
        closed_limit=True,
        board_height=1,
        amount=5_330_000_000,
        turnover_rate=8.1,
        industry="半导体",
        concept="AI 芯片",
        next_open_pct=3.6,
        next_high_pct=11.2,
        next_close_pct=8.8,
        three_day_return_pct=12.5,
        five_day_return_pct=16.1,
        continued_next_day=True,
    ),
]
